volumes:
  postgres_volume:

services:
  chat-server-pg:
    image: postgres:17.5-alpine3.22
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume:/b/micro-project/chat-server/postgres
